### ISSUE TITLE
Reexportar loadParams 

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-angular#153]
**What would you like to be added**:
Reexportar loadParams que está definido no core para que o usuário final possa importar da lib que ele mesmo instalou, no caso beagle-angular, ao invés de importar do web que ele não instalou diretamente.

**Why is this needed**:
Evitar confusões para o usuário final na hora de usar

**Comment by Tiagoperes** [comment]
loadParams foi depreciado.

Hoje, na aplicação final, acabamos com uma combinação de imports do `beagle-angular` e do `beagle-web`.

Exportar só o ActionHandler não acho que faça muito sentido, já que ainda teríamos que importar outras coisas do `beagle-web`.

Ou mantemos separadas essas importações ou, no Beagle Angular, fazemos `export * from 'beagle-web'`, de forma que tudo que existe no beagle-web possa ser importado a partir do beagle-angular.
