### ISSUE TITLE
Combining default and application config components breaks application

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-angular#193]
Beagle Angular version: 1.2.0

## Steps To Reproduce

1. In the beagle config, create a custom component key associated with one default component, for example: 
`'custom:bxContainer': BeagleContainerComponent,`

2. When trying to run the application, the application doesn't run and shows the following error:
`ERROR in Reference "#beagleContainer" is defined several times ("</ng-template>
  <ng-template [ERROR ->]#beagleContainer let-onInit="tree.onInit" let-screenAnalyticsEvent="tree.screenAnalyticsEvent" let-st")`

The problem is not different keys associated with the same component. The code below represents a valid config for different components using the same component defined in the config file:
`'beagle:text': BxTextComponent,
    'custom:bxText': BxTextComponent,`

I noticed that if the user wants to use a beagle default component also with a custom key, the config should have all the key value pairs that use that component, for the container example above, it is possible to fix defining the following components in the config:
`'custom:bxContainer': BeagleContainerComponent,
    'beagle:container': BeagleContainerComponent,
    'beagle:screencomponent': BeagleContainerComponent,
    'beagle:scrollview': BeagleContainerComponent,`

The problem only occurs when the same component after combining the default and user components has entries from both.

**Comment by carolinegoncalveszup** [comment]
Debugging the application I noticed that the map of the components to be considered have different definitions if they are only defined in the beagle angular lib, if the are defined in the beagle angular and override in the user application and if they are only defined in the user application. 
For instance:

- Components defined only in the beagle angular lib

```
'custom:error': [Function: BeagleErrorComponent], 
'custom:loading': [Function: BeagleLoadingComponent],
```

- Components defined in beagle angular and used in the user app: 

```
'beagle:futurelistview': [Function: BeagleFutureListViewComponent] {
    ctorParameters: [Function]
  },
 'beagle:container': [Function: BeagleContainerComponent] { 
	ctorParameters: [Function] 
 },
```

- Components defined only in the user application:

```
'beagle:button': [Function: BxButtonComponent] {
    decorators: [ [Object] ],
    propDecorators: { text: [Array], styleId: [Array], onPress: [Array] }
  },
```

**Comment by hectorcustodiozup** [comment]
The problem doesn't occur when importing the component direct from its folder in the core library 
`import { BeagleContainerComponent } from '@zup-it/beagle-angular/components/beagle-container/beagle-container.component'`

The shortcuts seems to be the problem but I could not find out why, tried changing the way it was being exported but without success.
