### ISSUE TITLE
Beagle angular doesn't work with angular 11

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-angular#219]
Beagle Angular version: 1.4.1

## Steps To Reproduce

1. Created a new project with angular cli using angular version 11
2. Tried to install beagle web angular
3. The following error is shown
![Image_20201112_175944](https://user-images.githubusercontent.com/47392346/99068161-bbb75180-258a-11eb-9d29-c75a47913a9d.jpeg)

**Comment by pedroskakum** [comment]
I have the same problem

**Comment by Tiagoperes** [comment]
We'll check it out as soon as possible. For now, we recommend using Angular 10.

**Comment by hectorcustodiozup** [comment]
Tested on windows, could not replicate the error. All I got was a warning about the dependency 
![image](https://user-images.githubusercontent.com/50678762/99680633-07bb3800-2a5c-11eb-819b-51f74ad164f6.png)

ng --version:
![image](https://user-images.githubusercontent.com/50678762/99680782-2cafab00-2a5c-11eb-92eb-e6b388d1c4fd.png)
