### ISSUE TITLE
Upgrade angular to at least 10.1.1

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-angular#262]
Related: https://github.com/ZupIT/beagle-web-angular/security/dependabot/package.json/ng-packagr/open

According to the link above, we need to upgrade the ng-packagr to version 10.1.1. To do this, we need to upgrade Angular as a whole. This might be a problem, since we need to support versions as low as Angular 7.

To solve this issue, we must upgrade our Angular version to at least 10.1.1 and verify if the lib keeps working with projects using older versions, like Angular 7, 8 or 9.

It would be nice if we has an automatic process that tests a simple project using every version of Angular that we support. This is not necessary to solve this issue, but an interesting addition.

Furthermore, our current dependency on Angular states that we need Angular 6 and above. This is wrong, we need Angular 7 and above. Please, also fix this while solving this issue.

**Comment by gabrielpenhazup** [comment]
Result of my tests with the lib in the version 10.2.3:
Angular 7 - returned error `Class constructor abstractBeagleRemoteView cannot be invoked without 'new'`
Angular 8 - did not run
Angular 9, 10, 11, 12 - it worked
