### ISSUE TITLE
Beagle doesn't work with Angular 12

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-angular#263]
Beagle Angular version: 1.7

## Steps To Reproduce

1. Using the Angular Cli 12, create a new app via `ng new` command
2. Install and set up Beagle according to the documentation

## The current behavior
The code fails to compile

## The expected behavior
I expected it to work

**Comment by Tiagoperes** [comment]
We officially support Angular from versions 7 to 10. We should increase 10 to 12.

**Comment by gabrielpenhazup** [comment]
Using Angular CLI 12 on Windows, I tested all Beagle components and it worked correctly
