### ISSUE TITLE
Utilizar beagle-remote-view componentes dinâmicos modo AOT

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-angular#3]
Ao utilizar o beagle-remote-view em um componente do módulo de componentes dinâmicos que foi passado nas configs:

- rodando com JIT funciona corretamente
- rodando no AOT ele não reconhece as props do beagle-remote-view

**Comment by Tiagoperes** [comment]
A solução utilizada hoje não faz diferença ente AOT e JIT
